version: "3.8"

services:
  backend:
    build: ./server
    container_name: buecher_backend
    command: npm run dev
    ports:
      - "3000:3000"
    env_file:
      - ./server/.env
    depends_on:
      - mongo
    volumes:
      - ./server:/app
      - /app/node_modules

  frontend:
    build: ./frontend
    container_name: buecher_frontend
    command: npm start
    ports:
      - "8080:8080"     # ui5 serve
      - "35729:35729"   # livereload websocket
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules

  mongo:
    image: mongo:6
    container_name: buecher_mongo
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db

  # nginx:
  #   image: nginx:1.27-alpine
  #   container_name: buecher_nginx
  #   ports:
  #     - "8080:80"
  #   depends_on:
  #     - frontend
  #     - backend
  #   volumes:
  #     - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

volumes:
  mongo_data:
